spring:
  # ????????
  application:
    name: BChat                                       # ????

  #
  # ????MySQL???
  #
  datasource:
    url: jdbc:mysql://localhost:3306/bchat            # MySQL ????? URL
    username: root                                    # ??????
    password: 123456                                  # ?????
    driver-class-name: com.mysql.cj.jdbc.Driver      # MySQL ???

    # ???????HikariCP???
    hikari:
      maximum-pool-size: 10                           # ?????????
      minimum-idle: 5                                 # ???????????
      idle-timeout: 30000                             # ????????????????????
      connection-timeout: 30000                       # ???????????????????????
      max-lifetime: 1800000                           # ?????????????????????

  #
  # Redis ????
  #
  data:
    redis:
      host: localhost                                # Redis ?????
      port: 6379                                     # Redis ???
      timeout: 5000                                  # ??????????

  #
  # JPA ?????? Hibernate?
  #
  jpa:
    hibernate:
      ddl-auto: update                               # ?????????????????????? `validate`?
    show-sql: true                                  # ???????? SQL ???????????
    open-in-view: false                             # ???? Open Session In View?false ?????????????????????

# ???????
server:
  port: 8864                                        # ???????

#
# Knife4j?Swagger ?? UI???
#
knife4j:
  enable: true                                      # ???? Knife4j ??
  production: false                                 # ?????????false ????????? API ???

#
# JWT ????
#
app:
  jwt-secret: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"  # JWT ??????????????????
  jwt-expiration-milliseconds: 604800000                                          # Token ?????????7 ??7 * 24 * 60 * 60 * 1000?

# ?????????????
# logging:
#   level:
#     root: debug                                 # ????????? debug
